/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion.interfaceG;
  import org.apache.logging.log4j.LogManager;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Font;
import com.itextpdf.text.pdf.draw.LineSeparator;
import gestion.stock.ResultSetTableModel;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.rendering.PDFRenderer;
import java.io.File;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import javax.swing.JFrame;

/**
 *
 * @author Administrator
 */
public class depenses extends javax.swing.JFrame {

    /**
     * Creates new form Facture
     */
    ResultSet rslt=null;
    BDD base_donne;
    
    public depenses() throws ClassNotFoundException, SQLException {
        initComponents();
        this.setBounds(200, 300, 920, 580);
        base_donne=new BDD();
        this.setResizable(false);
       
        date_set();
       combox_remplissage();
       combox_mois_remplissage();
        afficherTable();
        
        
    }
    public void total_table(){
        int lastRow = table_depense.getRowCount() - 1;
    int lastColumn = table_depense.getColumnCount() - 1;
    total_lbl.setText( String.valueOf( table_depense.getValueAt(lastRow, lastColumn)));
    
    
    }
    public void impression(){
        File folder=new File ("infor_gestion/bilan");
        if (!folder.exists()){
        folder.mkdir();
        }
        Date d1=new Date();
        String nom_fichier="/*infor_gestion/bilan/Bilan_du_"+d1.toString()+".pdf";
        Font fontTitre;
        fontTitre = new Font(Font.FontFamily.TIMES_ROMAN,16,Font.BOLD,BaseColor.BLUE);
        
        Font Invoice_font=new Font(Font.FontFamily.TIMES_ROMAN,14,Font.BOLD,BaseColor.BLUE);
        LineSeparator ls =new LineSeparator();
        ls.setLineColor(BaseColor.WHITE);
        
        
        
    
    }
    
    
    
    public void afficherTable() throws ClassNotFoundException, SQLException {
    String[] colonnes = {"id","code_produit","ref","designation","fournisseur","remise","prix_unitaire","stock","date"};
    rslt = base_donne.RecupererDonne("SELECT id, libele,DATE_FORMAT(date, '%Y-%m-%d')As date , montant,\n" +
"       @cumul := @cumul + montant AS cumul\n" +
"FROM depenses, (SELECT @cumul := 0) c\n" +
"ORDER BY date");
    
    
    // Créer un modèle de tableau avec le ResultSet
    
    // Définir le modèle de tableau sur le composant table_user
    table_depense.setModel(new ResultSetTableModel(rslt));
    total_table();}
    public void combox_remplissage() throws SQLException, ClassNotFoundException {
        rslt = base_donne.RecupererDonne("SELECT DISTINCT date FROM depenses order by -id");
        date_search_field.removeAllItems();
        while (rslt.next()) {

            date_search_field.addItem(rslt.getString("date"));

        }
        rslt.close();

    }
   public void combox_mois_remplissage() throws SQLException, ClassNotFoundException {
        rslt = base_donne.RecupererDonne("SELECT DISTINCT DATE_FORMAT(date, '%Y-%m') AS mois_annee FROM depenses order by -id");
        moi_field.removeAllItems();
        while (rslt.next()) {
           moi_field.addItem(rslt.getString("mois_annee"));

        }
        rslt.close();

    }
   
public void date_set() {
        Date d = new Date();
        SimpleDateFormat dat1 = new SimpleDateFormat("EEEE-dd-MMM-yyy");
        SimpleDateFormat dat2 = new SimpleDateFormat("HH:mm");
        date_field.setText(dat1.format(d));
        heure_field.setText(dat2.format(d));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        montant_field = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        libele_field = new javax.swing.JTextField();
        heure_field = new javax.swing.JLabel();
        date_field = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        date_search_field = new javax.swing.JComboBox<>();
        add_btn = new javax.swing.JButton();
        modifier_btn = new javax.swing.JButton();
        supprimer_btn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_depense = new javax.swing.JTable();
        chercher = new javax.swing.JButton();
        total_lbl = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        moi_field = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        imprimer = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        vendre_e = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        Retour = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(java.awt.Color.orange);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Depenses");

        jLabel2.setText("Libele");

        jLabel3.setText("Montant");

        heure_field.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        heure_field.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        date_field.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        date_field.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Date");

        date_search_field.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        add_btn.setText("Ajouter");
        add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btnActionPerformed(evt);
            }
        });

        modifier_btn.setText("Modifier");
        modifier_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifier_btnActionPerformed(evt);
            }
        });

        supprimer_btn.setText("Supprimer");
        supprimer_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimer_btnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Journée du");

        jLabel8.setText("Montant");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(add_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(modifier_btn)
                        .addGap(72, 72, 72))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 89, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(montant_field, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(libele_field, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(83, 83, 83)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(supprimer_btn)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(date_search_field, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(heure_field, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(date_field, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(86, 86, 86))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(date_field, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(heure_field, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(libele_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(montant_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date_search_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_btn)
                    .addComponent(modifier_btn)
                    .addComponent(supprimer_btn)
                    .addComponent(jLabel4)))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 920, 251);

        jPanel2.setBackground(new java.awt.Color(51, 204, 255));
        jPanel2.setLayout(null);

        table_depense.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Libele", "Date", "Montant ", "Cumul"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_depense.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_depenseMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_depense);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 80, 700, 120);

        chercher.setText("Chercher");
        chercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chercherActionPerformed(evt);
            }
        });
        jPanel2.add(chercher);
        chercher.setBounds(740, 0, 110, 29);

        total_lbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        total_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        total_lbl.setText("0");
        jPanel2.add(total_lbl);
        total_lbl.setBounds(450, 200, 270, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Total");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(340, 210, 90, 22);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Par mois");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(650, 40, 70, 30);

        moi_field.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        moi_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moi_fieldActionPerformed(evt);
            }
        });
        jPanel2.add(moi_field);
        moi_field.setBounds(740, 40, 110, 26);

        jButton1.setText("Rechercher");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(740, 80, 120, 29);

        imprimer.setText("Imprimer");
        imprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimerActionPerformed(evt);
            }
        });
        jPanel2.add(imprimer);
        imprimer.setBounds(20, 220, 130, 50);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 243, 920, 340);

        jMenuBar1.setBackground(java.awt.Color.orange);

        jMenu2.setText("Menu");

        vendre_e.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        vendre_e.setText("Vendre");
        vendre_e.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendre_eActionPerformed(evt);
            }
        });
        jMenu2.add(vendre_e);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText("Voir le bilan");
        jMenu2.add(jMenuItem5);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Voir les vendeurs");
        jMenu2.add(jMenuItem4);

        jMenuItem6.setText("Voir");
        jMenu2.add(jMenuItem6);

        Retour.setText("Retour");
        jMenu2.add(Retour);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Quiter");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btnActionPerformed
        // TODO add your handling code here:
        if (libele_field.getText().equals("")|| montant_field.getText().equals("")){
             JOptionPane.showMessageDialog(this,"veuillez renseigner tous les champs");
        
        }else {
            if(JOptionPane.showConfirmDialog(this,"êtes-vous Sûr d'avoir depenser cet argent","warning",JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION){
                try {
                     String[] colonne ={"libele","montant"};
                    String[] donne={libele_field.getText(),montant_field.getText()};
                    base_donne.InsererParColns("depenses", colonne, donne);
                    afficherTable();
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(depenses.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(depenses.class.getName()).log(Level.SEVERE, null, ex);
                }
                 
                
        
        }else{
        return;
        }
        
        
        
        
        
        }
        
        
    }//GEN-LAST:event_add_btnActionPerformed

    String date=null;
    
    
    private void modifier_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifier_btnActionPerformed
        // TODO add your handling code here:
        if (libele_field.getText().equals("")|| montant_field.getText().equals("")){
             JOptionPane.showMessageDialog(this,"veuillez renseigner tous les champs");
               }else{
                if(JOptionPane.showConfirmDialog(this,"êtes-vous Sûr d'avoir depenser cet argent","warning",JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION){
                    String[] colonne ={"libele","montant","date"};
                    String[] donne={libele_field.getText(),montant_field.getText(),date};
                    String id= String.valueOf(table_depense.getValueAt(table_depense.getSelectedRow(),0));
                    base_donne.updateDonneTable("depenses", colonne,donne,"id='"+id+"'");
                    try {
                        afficherTable();
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(depenses.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (SQLException ex) {
                        Logger.getLogger(depenses.class.getName()).log(Level.SEVERE, null, ex);
                    }
                 
             
        
        
        }}
    }//GEN-LAST:event_modifier_btnActionPerformed

    private void table_depenseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_depenseMouseClicked
        // TODO add your handling code here:
        
        libele_field.setText(String.valueOf(table_depense.getValueAt(table_depense.getSelectedRow(),1)));
        montant_field.setText(String.valueOf(table_depense.getValueAt(table_depense.getSelectedRow(),3)));
        date=String.valueOf(table_depense.getValueAt(table_depense.getSelectedRow(),2));
        
    }//GEN-LAST:event_table_depenseMouseClicked

    private void chercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chercherActionPerformed
        try {
            // TODO add your handling code here:
            rslt = base_donne.RecupererDonne("SELECT id, libele,date, montant,\n" +
                    "       @cumul := @cumul + montant AS cumul\n" +
                    "FROM depenses, (SELECT @cumul := 0) c\n" +
                    " WHERE date LIKE '%"+date_search_field.getSelectedItem().toString()+"%' ORDER BY date");
               table_depense.setModel(new ResultSetTableModel(rslt));
    total_table();
            
        } catch (SQLException ex) {
            Logger.getLogger(depenses.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(depenses.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    
    // Créer un modèle de tableau avec le ResultSet
    
    // Définir le modèle de tableau sur le composant table_user
    table_depense.setModel(new ResultSetTableModel(rslt));
    total_table();
        
        
    }//GEN-LAST:event_chercherActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            try {
            // TODO add your handling code here:
            rslt = base_donne.RecupererDonne("SELECT id, libele,DATE_FORMAT(date, '%Y-%m-%d')As date , montant,\n" +
                    "       @cumul := @cumul + montant AS cumul\n" +
                    "FROM depenses, (SELECT @cumul := 0) c\n" +
                    " WHERE date LIKE '%"+moi_field.getSelectedItem().toString()+"%' ORDER BY date");
               table_depense.setModel(new ResultSetTableModel(rslt));
    total_table();
            
        } catch (SQLException ex) {
            Logger.getLogger(depenses.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(depenses.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    
    // Créer un modèle de tableau avec le ResultSet
    
    // Définir le modèle de tableau sur le composant table_user
    table_depense.setModel(new ResultSetTableModel(rslt));
        
    total_table();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void supprimer_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimer_btnActionPerformed
        // TODO add your handling code here:
        String id= String.valueOf(table_depense.getValueAt(table_depense.getSelectedRow(),0));
        if(JOptionPane.showConfirmDialog(this,"êtes-vous Sûr de supprimer","warning",JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION){
            try {
                base_donne.Delete("depenses","id ='"+id+"'");
                afficherTable();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(depenses.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(depenses.class.getName()).log(Level.SEVERE, null, ex);
            }
                
        
        }else{
        return;
        }
        try {
                
                
                afficherTable();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Utilisateur.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Utilisateur.class.getName()).log(Level.SEVERE, null, ex);
            }

        
    }//GEN-LAST:event_supprimer_btnActionPerformed

    private void vendre_eActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendre_eActionPerformed
        try {
            // TODO add your handling code here:
            Cahier e=new Cahier();
        } catch (SQLException ex) {
            Logger.getLogger(depenses.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(depenses.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_vendre_eActionPerformed

    private void moi_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moi_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moi_fieldActionPerformed
 public static void previewPDF(String filename) throws Exception {
         
 lecteurPDF lecteur = new lecteurPDF(filename);
 //créer le JFrame
 JFrame f = new JFrame("Lecteur PDF");
 f.setSize(1024,768);
 f.setLocationRelativeTo(null);
 f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
 f.setVisible(true);
 f.getContentPane().add(lecteur);
    }
    private void imprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimerActionPerformed
         SimpleDateFormat s = new SimpleDateFormat("ddMMyyyyHHmmss");
                Date date = new Date();
                String nom="pdf/table"+s.format(date).toString()+".pdf";
                
        try {                                         
            Document document = new Document();
            
            try {
                System.out.println(nom);
                try {
                    PdfWriter.getInstance(document, new FileOutputStream(nom));
                    
                } catch (DocumentException ex) {
                    Logger.getLogger(depenses.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(depenses.class.getName()).log(Level.SEVERE, null, ex);
            }
            document.open();
            document.addTitle("depense du"+date_field.getText());
            Paragraph paragraph = new Paragraph("Situation des depenses du"+date_field.getText());
            paragraph.setAlignment(Element.ALIGN_CENTER);
             document.add(paragraph);
             Paragraph espace = new Paragraph("");
            paragraph.setAlignment(Element.ALIGN_CENTER);
            document.add(espace);
            document.add(espace);
            
            
            PdfPTable pdfTable = new PdfPTable(table_depense.getColumnCount());
            
// Ajouter les en-têtes de colonne
for (int i = 0; i < table_depense.getColumnCount(); i++) {
    pdfTable.addCell(table_depense.getColumnName(i));
}

// Ajouter les données de la JTable
for (int rows = 0; rows < table_depense.getRowCount(); rows++) {
    for (int cols = 0; cols < table_depense.getColumnCount(); cols++) {
        pdfTable.addCell(table_depense.getModel().getValueAt(rows, cols).toString());
    }
}

document.add(pdfTable);
document.close();
            try {
                previewPDF(nom);
            } catch (Exception ex) {
                Logger.getLogger(depenses.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (DocumentException ex) {
            Logger.getLogger(depenses.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_imprimerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(depenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(depenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(depenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(depenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new depenses().setVisible(true);
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(depenses.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Retour;
    private javax.swing.JButton add_btn;
    private javax.swing.JButton chercher;
    private javax.swing.JLabel date_field;
    private javax.swing.JComboBox<String> date_search_field;
    private javax.swing.JLabel heure_field;
    private javax.swing.JButton imprimer;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField libele_field;
    private javax.swing.JButton modifier_btn;
    private javax.swing.JComboBox<String> moi_field;
    private javax.swing.JTextField montant_field;
    private javax.swing.JButton supprimer_btn;
    private javax.swing.JTable table_depense;
    private javax.swing.JLabel total_lbl;
    private javax.swing.JMenuItem vendre_e;
    // End of variables declaration//GEN-END:variables
}
